# 2. Introduction to Pandas

### References: 
* <a href="https://pandas.pydata.org/">Pandas website</a>
* <a href="https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html">User Guide</a>
* <a href="https://pandas.pydata.org/pandas-docs/stable/reference/series.html">API Reference - Series</a>
* <a href="https://pandas.pydata.org/pandas-docs/stable/reference/frame.html">API Reference - DataFrame</a>

Pandas is a Python package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive.It aims to be the fundamental high-level building block for doing practical, real world data analysis in Python.

## 2.1 Import Pandas library

In [68]:
import pandas as pd

Pandas is well suited for many different kinds of data:
* <b>Tabular data</b> with heterogeneously-typed columns, as in an SQL table or Excel spreadsheet
* Ordered and unordered (not necessarily fixed-frequency) <b>time series data</b>.
* Arbitrary <b>matrix data</b> (homogeneously typed or heterogeneous) with row and column labels
* Any other form of observational / statistical data sets. The data actually need not be labeled at all to be placed into a pandas data structure

Data structures in pandas are:

* <b>`Series`</b> objects: 1D array, similar to a column in a spreadsheet
* <b>`DataFrame`</b> objects: 2D table, similar to a spreadsheet
* <b>Panel objects</b>: Dictionary of DataFrames, similar to sheet in MS Excel

## 2.2 Series

Pandas Series is a <span style="color: red;">one-dimensional labeled array</span> capable of holding data of any type (integer, string, float, python objects, etc.). The axis labels are collectively called index. Pandas Series is nothing but <span style="color: red;">a column</span> in an excel sheet. Labels need not be unique but must be a hashable type (i.e. a label hash some value which never changes). The object supports both integer and label-based indexing and provides a host of methods for performing operations involving the index.

![series](https://media.geeksforgeeks.org/wp-content/uploads/20200225170506/pandas-series.png)

### 2.2.1 Create a Serie

<u>In the real world, a Pandas Series will be created by loading the datasets from existing storage, storage can be SQL Database, CSV file, and Excel file. Pandas Series can be created from the lists, dictionary, etc.</u>

We can easily create a Pandas `Series` from a NumPy array:

In [70]:
import pandas as pd
import numpy as np

ndarray = np.array(['a','b','c','d'])
serie = pd.Series(ndarray)
print(serie)

0    a
1    b
2    c
3    d
dtype: object

Or simply by declaring it

In [72]:
data = pd.Series([1, 2, 3, 4, 5])
print(data)

0    1
1    2
2    3
3    4
4    5
dtype: int64

The indices can be integers like in the example above. Alternatively, the indices can be labels.

In [74]:
data_1 = [1,2,3]
index_1 = ['a', 'b', 'c']
data = pd.Series(data_1, index=index_1)
data

a    1
b    2
c    3
dtype: int64

Also, `Series` can be easily created from dictionaries

In [76]:
dictionary = {'A':5, 'B':3, 'C':1}
data = pd.Series(dictionary)
data

A    5
B    3
C    1
dtype: int64

## 2.3 DataFrame

If a `Series` is a one-dimensional indexed array, the `DataFrame` is a <span style="color: red;">two-dimensional indexed array</span>. It can be thought of as a collection of Series objects, where each Series represents a column, or as an enhanced 2D numpy array. 

In a `DataFrame`, the index refers to labels for each row, while columns describe each column.

![dataframe](https://media.geeksforgeeks.org/wp-content/uploads/20200225170602/pandas-dataframe.png)

### 2.3.1 Create a data frame

<u>Just like Series, In the real world, a Pandas DataFrame will be created by loading the datasets from existing storage, storage can be SQL Database, CSV file, and Excel file. Pandas DataFrame can be created from the lists, dictionary, and from a list of dictionary etc.</u>

First, let's create a `DataFrame` using random numbers generated from numpy.

In [78]:
import numpy as np
numpy_array = np.random.random((5, 3))
numpy_array
data = pd.DataFrame(numpy_array)
data

          0         1         2
0  0.587543  0.625607  0.457186
1  0.638861  0.264158  0.204704
2  0.696664  0.563495  0.121557
3  0.741125  0.536656  0.832383
4  0.576629  0.721347  0.150631

We could also initialize with column names

In [80]:
data = pd.DataFrame(np.random.random((5, 3)), columns=['A', 'B', 'C'])
data

          A         B         C
0  0.502128  0.278483  0.705991
1  0.494910  0.728494  0.388801
2  0.108075  0.589325  0.679585
3  0.794908  0.985943  0.302829
4  0.169456  0.257015  0.591610

Alternatively, we could create a `DataFrame` from multiple `Series` objects.

In [82]:
a = pd.Series([1, 2, 3, 4])
#a = [1,2,3,4]
b = pd.Series(['a', 'b', 'c', 'd'])
#b = ['a', 'b', 'c', 'd']
data = pd.DataFrame({'Numbers':a, 'Letters':b})
#data.index = ['A', 'B', 'C', 'D']
data

   Numbers Letters
0        1       a
1        2       b
2        3       c
3        4       d

Or a python dictionary

In [84]:
data = pd.DataFrame({'Region':['AML', 'North', 'Center', 'Alentejo', 'Algarve', 'Azores', 'Madeira'], 
                     'Cidades':['Lisbon', 'Porto', 'Coimbra', 'Beja', 'Faro', 'Ponta Delgada', 'Funchal']}, 
                    index=['AML', 'NOR', 'CEN', 'ALE', 'ALG', 'AZO', 'MAD'])
data

       Region        Cidades
AML       AML         Lisbon
NOR     North          Porto
CEN    Center        Coimbra
ALE  Alentejo           Beja
ALG   Algarve           Faro
AZO    Azores  Ponta Delgada
MAD   Madeira        Funchal

### 2.3.2 DataFrame - More examples

In [86]:
doggos = [
        ['Peter Parker','Doberman',3],
        ['John Reese','Golden Retriever',8],
        ['Bill Gates','Poodle',6],
        ['Mary Poppins','Beagle',1],
        ['Phoebe Buffay','Chihuahua',4],
        ['Sheldon Cooper','Husky siberiano',10],
        ['Patrick Jane','Husky siberiano',14]
]
doggos

[['Peter Parker', 'Doberman', 3],
 ['John Reese', 'Golden Retriever', 8],
 ['Bill Gates', 'Poodle', 6],
 ['Mary Poppins', 'Beagle', 1],
 ['Phoebe Buffay', 'Chihuahua', 4],
 ['Sheldon Cooper', 'Husky siberiano', 10],
 ['Patrick Jane', 'Husky siberiano', 14]]

In [88]:
doggos_df=pd.DataFrame(doggos,columns=['Name','Breed','Age'])
doggos_df

             Name             Breed  Age
0    Peter Parker          Doberman    3
1      John Reese  Golden Retriever    8
2      Bill Gates            Poodle    6
3    Mary Poppins            Beagle    1
4   Phoebe Buffay         Chihuahua    4
5  Sheldon Cooper   Husky siberiano   10
6    Patrick Jane   Husky siberiano   14

### 2.3.3 Previewing the data frame

[**DataFrame.head(n=5)**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.head.html#pandas.DataFrame.head)
* This function returns the first n rows for the object based on position. It is useful for quickly testing if your object has the right type of data in it

In [90]:
doggos_df.head(4)

           Name             Breed  Age
0  Peter Parker          Doberman    3
1    John Reese  Golden Retriever    8
2    Bill Gates            Poodle    6
3  Mary Poppins            Beagle    1

[**DataFrame.tail(n=5)**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.tail.html#pandas.DataFrame.tail)
* This function returns last n rows from the object based on position. It is useful for quickly verifying data, for example, after sorting or appending rows

In [92]:
doggos_df.tail(3)

             Name            Breed  Age
4   Phoebe Buffay        Chihuahua    4
5  Sheldon Cooper  Husky siberiano   10
6    Patrick Jane  Husky siberiano   14

[**DataFrame.shape**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.shape.html#pandas.DataFrame.shape)
* Return a tuple representing the dimensionality of the DataFrame.

In [94]:
doggos_df.shape

(7, 3)

In [96]:
len(doggos_df)

7

[**DataFrame.columns**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.columns.html#pandas.DataFrame.columns)
* The column labels of the DataFrame

In [98]:
doggos_df.columns

Index(['Name', 'Breed', 'Age'], dtype='object')

[**DataFrame.dtypes**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dtypes.html#pandas.DataFrame.dtypes)
* Return the dtypes in the DataFrame.
* This returns a Series with the data type of each column.
* The result’s index is the original DataFrame’s columns.
* Columns with mixed types are stored with the object dtype.

In [100]:
doggos_df.dtypes

Name     object
Breed    object
Age       int64
dtype: object

[**DataFrame.values**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.values.html#pandas.DataFrame.values)
* Return a Numpy representation of the DataFrame.
* Python documentation recommends using DataFrame.to_numpy() instead.
* Only the values in the DataFrame will be returned, the axes labels will be removed.

In [102]:
doggos_df.values

array([['Peter Parker', 'Doberman', 3],
       ['John Reese', 'Golden Retriever', 8],
       ['Bill Gates', 'Poodle', 6],
       ['Mary Poppins', 'Beagle', 1],
       ['Phoebe Buffay', 'Chihuahua', 4],
       ['Sheldon Cooper', 'Husky siberiano', 10],
       ['Patrick Jane', 'Husky siberiano', 14]], dtype=object)

### 2.3.4 Some Statistics

The DataFrame member function [`describe`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html) provides useful summary statistics such as the total number of samples, mean, standard deviations, min/max, and quartiles for each column of the DataFrame.

[**DataFrame.describe(percentiles=None, include=None, exclude=None)**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html#pandas.DataFrame.describe)
* Generate descriptive statistics that summarize the central tendency, dispersion and shape of a dataset’s distribution, excluding NaN values.
* Analyzes both numeric and object series, as well as DataFrame column sets of mixed data types. The output will vary depending on what is provided.

In [104]:
some_stats = doggos_df.describe()
some_stats

             Age
count   7.000000
mean    6.571429
std     4.466809
min     1.000000
25%     3.500000
50%     6.000000
75%     9.000000
max    14.000000

[**Series.value_counts(normalize=False, sort=True, ascending=False, bins=None, dropna=True)**](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html)
* Return a Series containing counts of unique values.
* The resulting object will be in descending order so that the first element is the most frequently-occurring element. Excludes NA values by default.

In [106]:
doggos_df['Breed'].value_counts()

Breed
Husky siberiano     2
Doberman            1
Golden Retriever    1
Poodle              1
Beagle              1
Chihuahua           1
Name: count, dtype: int64

## 2.4 Loading Data
Pandas offers some of the best utilities available for reading/parsing data from text files. The function read_csv has numerous options for managing header/footer lines in files, parsing dates, selecting specific columns, etc in comma separated value (CSV) files. The default index for the Dataframe is set to a set of monotonically increasing integers unless otherwise specified with the keyword argument `index_col`.

There are similar functions for reading Microsoft Excel spreadsheets (read_excel) and fixed width formatted text (read_fwf).

Loading data is fairly straightfoward in Pandas. Type `pd.read` then press tab to see a list of functions that can load specific file formats such as: csv, excel, spss, and sql.

In this example, we will use `pd.read_csv` to load a .csv file into a dataframe. 
Note that read_csv() has many options that can be used to make sure you load the data correctly. You can explore the docstrings for a function to get more information about the inputs and general useage guidelines by running `pd.read_csv?`

In [ ]:
pd.read_csv?

To load a csv file we will need to specify either the relative or absolute path to the file.

The command `pwd` will print the path of the current working directory.

In [108]:
pwd

'/Users/tomasamorimesa/Documents/work/jobs/iscte/FCD_1S_2025/5_Semana'

We will now load the Pandas has many ways to read data different data formats into a dataframe.  Here we will use the `pd.read_csv` function.

In [110]:
cars = pd.read_csv('cars.csv', sep=';')

## 2.5 Exercises

All the exercises below are based on the dataset `cars.csv` from Class 4

a) Present the content of the first 5 lines:

In [112]:
cars.head(5)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8,307.0,130.0,3504.0,12.0,70,US
1,Buick Skylark 320,15.0,8,350.0,165.0,3693.0,11.5,70,US
2,Plymouth Satellite,18.0,8,318.0,150.0,3436.0,11.0,70,US
3,AMC Rebel SST,16.0,8,304.0,150.0,3433.0,12.0,70,US
4,Ford Torino,17.0,8,302.0,140.0,3449.0,10.5,70,US

b) Present the content of the last 10 lines:

In [114]:
cars.tail(10)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
396,Chrysler Lebaron Medallion,26.0,4,156.0,92.0,2585.0,14.5,82,US
397,Ford Grenada l,22.0,6,232.0,112.0,2835.0,14.7,82,US
398,Toyota Celica GT,32.0,4,144.0,96.0,2665.0,13.9,82,Japan
399,Dodge Charger 2.2,36.0,4,135.0,84.0,2370.0,13.0,82,US
400,Chevrolet Camaro,27.0,4,151.0,90.0,2950.0,17.3,82,US
401,Ford Mustang GL,27.0,4,140.0,86.0,2790.0,15.6,82,US
402,Volkswagen Pickup,44.0,4,97.0,52.0,2130.0,24.6,82,Europe
403,Dodge Rampage,32.0,4,135.0,84.0,2295.0,11.6,82,US
404,Ford Ranger,28.0,4,120.0,79.0,2625.0,18.6,82,US
405,Chevy S-10,31.0,4,119.0,82.0,2720.0,19.4,82,US

c) Which models of cars have more occurrences?

In [116]:
cars['Car'].value_counts()

Car
Toyota Corolla                9
Ford Pinto                    6
Ford Maverick                 5
AMC Matador                   5
Volkswagen Rabbit             5
                             ..
Plymouth Grand Fury           1
Chevrolete Chevelle Malibu    1
Plymouth Fury                 1
Buick Skyhawk                 1
Chevy S-10                    1
Name: count, Length: 308, dtype: int64

d) How many cars are of European origin?

In [118]:
#cars['Origin'].value_counts()
#cars[cars["Origin"] == 'Europe'].counts()
(cars["Origin"] == 'Europe').value_counts()

Origin
False    333
True      73
Name: count, dtype: int64

d1) Filter out all cars of European origin

In [120]:
cars[cars["Origin"] == 'Europe']

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
10,Citroen DS-21 Pallas,0.0,4,133.0,115.0,3090.0,17.5,70,Europe
25,Volkswagen 1131 Deluxe Sedan,26.0,4,97.0,46.0,1835.0,20.5,70,Europe
26,Peugeot 504,25.0,4,110.0,87.0,2672.0,17.5,70,Europe
27,Audi 100 LS,24.0,4,107.0,90.0,2430.0,14.5,70,Europe
28,Saab 99e,25.0,4,104.0,95.0,2375.0,17.5,70,Europe
...,...,...,...,...,...,...,...,...,...
366,Peugeot 505s Turbo Diesel,28.1,4,141.0,80.0,3230.0,20.4,81,Europe
367,Saab 900s,0.0,4,121.0,110.0,2800.0,15.4,81,Europe
368,Volvo Diesel,30.7,6,145.0,76.0,3160.0,19.6,81,Europe
383,Volkswagen Rabbit l,36.0,4,105.0,74.0,1980.0,15.3,82,Europe
402,Volkswagen Pickup,44.0,4,97.0,52.0,2130.0,24.6,82,Europe

e) Present some statistics about the dataset.

In [122]:
some_stats = cars.describe()
some_stats

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model
count,406.000000,406.000000,406.000000,406.000000,406.000000,406.000000,406.000000
mean,23.051232,5.475369,194.779557,103.529557,2979.413793,15.519704,75.921182
std,8.401777,1.712160,104.922458,40.520659,847.004328,2.803359,3.748737
min,0.000000,3.000000,68.000000,0.000000,1613.000000,8.000000,70.000000
25%,17.000000,4.000000,105.000000,75.000000,2226.500000,13.700000,73.000000
50%,22.350000,4.000000,151.000000,93.500000,2822.500000,15.500000,76.000000
75%,29.000000,8.000000,302.000000,129.000000,3618.250000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000